server:
  port: 9296

application:
  file:
    location: C:\\file.txt
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mhmdfyk/Config-Server
          clone-on-start: true